# Generated by Django 3.1.1 on 2021-06-09 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='application_id',
            field=models.PositiveIntegerField(default=123456, unique=True, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
