# Generated by Django 3.1.1 on 2021-06-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210609_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='application_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
